name: hyperion-build-actions
on: [push]
jobs:
  run-maven-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['11', '15']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2           # checks out of repository and download it to the runner
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1 # installing graphviz
      - uses: actions/setup-java@v2         # installing java
        with:
          distribution: 'adopt'             # Java distribution
          java-version: ${{ matrix.java }}  # Java version
          check-latest: true                # Checking that cached version is the latest
      - run: mvn --batch-mode
      - uses: codecov/codecov-action@v1     # publishing code coverage results
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov for Java ${{ matrix.java }} on ${{ matrix.os }}
